require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '11.0'

target 'Donut' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  
  pod 'secp256k1.c', '0.1.2', :modular_headers => true
  pod 'web3swift', '2.2.1', :modular_headers => true

  target 'DonutTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Donut-tvOS' do
  # Pods for Donut-tvOS

  target 'Donut-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
